name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-2204
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: apt-get update; apt-get -y --install-suggests install graphviz
    - name: Build
      run: make
