name: make

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get -y update
    - run: sudo apt-get install -y --install-suggests graphviz
    - run: make
    - uses: actions/deploy-pages@v1.2.3
